name: Parse url

on:
  schedule:
    # every 5 minutes, see https://crontab.guru
    - cron: '*/30 * * * *'
  #push:
  #  branches:
  #    - 'master'

jobs:
  build:
    name: Parse
    runs-on: ubuntu-latest
    steps:
      - name: Show Response
        id: get
        run: |
          curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
          python3 get-pip.py
          pip install requests
          pip install bs4

          # URL to fetch and parse
          url="https://etnodim.ua/zhinkam/ua-zhinochi-vishivanki/vyshyvanka-slovo"

          found_element=$(python3 - << EOF
          import requests
          from bs4 import BeautifulSoup
          import re

          url = "$url"
          pattern = r"XS"
          target_class = "unavailable"

          response = requests.get(url)
          html_content = response.text

          soup = BeautifulSoup(html_content, "html.parser")

          # Find all elements that match the text pattern using a regular expression and have the specified class
          matching_elements = soup.find_all("a", class_=['unavailable'], string=re.compile(pattern))

          if matching_elements:
            for element in matching_elements:
                if "js_product-fast-variant" not in element.get('class'):
                    print(0)
                    break
          else:
            print(1)
          EOF
          )

          echo "$found_element"

          echo "::set-output name=exists::$found_element"

      # see: https://push.techulus.com/
      - name: Send Push Notification
        uses: techulus/push-github-action@1.0.0
        if: ${{ steps.get.outputs.exists == 1 }}
        env:
          API_KEY: ${{ secrets.PUSH_SECRET }}
          MESSAGE: "XS available"
          TITLE: "Ura!"