name: Parse json url

on:
  schedule:
    # every 5 minutes, see https://crontab.guru
    - cron: '*/5 * * * *'
  push:
    branches:
      - 'master'
jobs:
  build:
    name: Parse
    runs-on: ubuntu-latest
    steps:
      - name: Make Request
        id: myRequest
        uses: fjogeleit/http-request-action@v1
        with:
          url: "https://bank.gov.ua/NBUStatService/v1/statdirectory/exchange?valcode=USD&json"
          method: GET

      - name: Show Response
        id: getRate
        run: |
          echo '${{ steps.myRequest.outputs.response }}'
          RATE=$(echo '${{ steps.myRequest.outputs.response }}' | jq '.[0].rate')
          echo "::set-output name=rate::${RATE}"

      - name: Notify
        #if: ${{ steps.getRate.outputs.rate > 28 }}
        run: |
          echo ${{ steps.getRate.outputs.rate }}
          echo ${{ steps.getRate.outputs.rate > 28 }}

      - name: Send Push Notification
        uses: techulus/push-github-action@1.0.0
        if: ${{ steps.getRate.outputs.rate > 28 }}
        env:
          API_KEY: ${{ secrets.PUSH_SECRET }}
          MESSAGE: "Dollar is above 35"
          TITLE: "Ura!"