name: Parse json url

on:
  schedule:
    # every 5 minutes, see https://crontab.guru
    - cron: '*/5 * * * *'
  push:
    branches:
      - 'master'
jobs:
  build:
    name: Parse
    runs-on: ubuntu-latest
    steps:
      - name: Make Request
        id: myRequest
        uses: fjogeleit/http-request-action@v1
        with:
          url: "https://bank.gov.ua/NBUStatService/v1/statdirectory/exchange?valcode=USD&json"
          method: GET

      - name: Show Response
        id: getRate
        run: |
          echo ${{ steps.myRequest.outputs.response }} | jq '.[0].rate
          echo "::set-output rate=29"

      - name: Notify
        if: ${{ steps.getRate.outputs.rate > 28 }}
        run: |
          echo "Great!"